apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: replicaset-spc
    namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
    spec:
      containers:
        - name: spc
          image: shashikamle/spc:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: replicaset-spc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: spc               
